### PR TITLE
DO NOT MERGE - for reference

### PR DESCRIPTION
**Pull request by johndpope**
fyi

- apologies for so many linting included in this (open separate PR)

I got the miner to mine and not crash on faster difficulties. 

Unfortunately - it's possible to still trip up depending on timing.
You may be able to get out of jail by adding a simple   sleep(1) to existing code. 

I took some extra steps in an attempt to bring some thread safety.

https://github.com/VKoskiv/VaporCoin/compare/master...johndpope:master

That includes SynchronizedArray + it's (exposed private) dispatch queue to share with the blockchain depth. Ideally - the state would be entirely thread safe.

### CODE REVIEW

**Comment by vkoskiv** [comment]
I don't have a style guide for this project - I'm just going off of Xcode defaults, and Swift styling.
It looks good, I'll resolve the conflicts + reindent and try it out

**Comment by johndpope** [comment]
If the comments / print statements are throttled - then it seems to happily mine away. 
21014 blocks in a few minutes.

**Comment by johndpope** [comment]
eventually the running queue runs out of things to do. 
screen shot 2018-01-10 at 3 37 32 pm

Taking a stab I think there's some edge case where there's a thread explosion. will keep digging. 
screen shot 2018-01-10 at 3 39 44 pm

**Comment by vkoskiv** [comment]
Merged, finally! I had made quite a few changes while you did yours, so took a bit of resolving. Looks great now!

**Comment by vkoskiv** [comment]
@johndpope Are you sure replacing `blockFound` with `taskGroup.leave()` is sufficient? I just noticed the block depth was 1 for two blocks. Could be that a block was found, and another thread continued to mine at the previous depth, and found a block.

**Comment by vkoskiv** [comment]
The idea with blockFound was to abort and restart all other theads when one thread found a block, so we update the other threads to start mining the next block instead of continuing the old one.
I hope that makes sense :P

**Comment by vkoskiv** [comment]
Alright, I tried reversing it, but even then for whatever reason, the state updates in `blockFound()` are not triggered, and so every block has a depth of 1 and the same prevHash

**Comment by vkoskiv** [comment]
After further testing, I reverted the merges for now.

**Comment by johndpope** [comment]
Makes more sense - there does exist an atomic Boolean idea - which I did attempt to switch into the mix. Will take a look tomorrow.

https://stackoverflow.com/questions/44685236/swift-3-atomic-boolean

**Pull request merged**
